apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: main-app-
resources:
- dns-endpoint.yaml
- deployment.yaml
- ingressroute.yaml
- secrets.yaml
- svc.yaml
commonLabels:
  app: main-app
